"use strict";
var userName = prompt( "Hello, what is your name?" );
console.log( userName + " has logged on to the site.");
var intro = prompt( "Hello " + userName + "! I bet you're here to learn about Joe. Would you like to play a quick guessing game to learn some neat stuff about him?" );
console.log( userName + " has said that " + intro + ", they want to play.");
var beer = prompt( "Would you believe he also likes to brew his own beer?");
console.log( "Response to beer prompt: " + beer );
var jewelry = prompt( "Did Joe's BFA from Central Washington University carry an emphasis on Jewelry and Metalsmithing?" );
console.log( "Response to jewelry prompt: " + jewelry );
var family = prompt( "In all this crazy stuff, did you realize that Joe is supported by his wife and two dogs?" );
console.log( "Response to family prompt: " + family );
var coding = prompt( "This is the end of the game. Based on what you saw, do you think Joe likes coding?" );
console.log( "Response to coding prompt: " + coding );
